//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Object_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carousel
    {
        public int id { get; set; }
        public string heading { get; set; }
        public string sub_heading { get; set; }
        public byte[] imageurl { get; set; }
        public System.DateTime created_at { get; set; }
        public string carousel_role { get; set; }
    }
}
