//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Object_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityAnswer
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int question_id { get; set; }
        public string answer { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual User User { get; set; }
    }
}
